### ISSUE TITLE
where is webapp repo

### ISSUE THREAD

**Issue by wanghaisheng** [alkasm/cspaceThresh#1]

**Comment by alkasm** [comment]
Still being worked on actually---had to put this on pause for some interviews in the Bay. [This is the repo](https://github.com/alkasm/cspaceFilter) for the python API and front-end, and [this is the repo](https://github.com/shaun-sweet/image-processing-ui) for the javascript. You can check out a current working version of the web app at [https://alkasm.github.io/cspaceFilter](https://alkasm.github.io/cspaceFilter/). However, the interface isn't finished yet so for now it just displays the images below the sliders.
